### ISSUE TITLE
Change title from ChronometricDate to ChronometricAge

### ISSUE THREAD

**Issue by lbrensk** [VertNet/dwc-chronology#1]
For consistency. Recommended by @dennereed.

"The extension is titled ChronometricDate but the terms mostly use Age, eg. verbatimChronometricAge. Perhaps consider changing the title of the extension to ChronometricAge to be consistent? or just Age? Likewise change chronometricDateID to chronometricAgeID."

**Comment by lbrensk** [comment]
I think this is a fair comment and seems to follow the changes that have happened more recently in the extension. I will make these changes. @tucotuco - I will make the changes on the GitHub files, and then can you do the XML part of this?

**Comment by tucotuco** [comment]
Yes, can do. But we should assemble all changes that are going to be made
into a single new release.

**Comment by tucotuco** [comment]
Changed in commit 1a5d8513887f2618f0bb6f1d1461051ed52a7c97
