### ISSUE TITLE
preferredChronometricAge?

### ISSUE THREAD

**Issue by lbrensk** [VertNet/dwc-chronology#2]
From @dennereed: "There’s terms for maximumChronometricAge and minimumChronometricAge. Consider adding preferredChronometricAge as well to represent the preferred single age associated with a specimen.  This would differ from verbatimChronometricAge. I can see an option where one sets max and min to the same value, but a separate term for preferredChronometricAge might be more clear."

I'm not quite sure I understand this recommendation as well so I am opening it up here for further discussion.

**Comment by mepenguin** [comment]
I may be out of context here, but I'm not sure there is such a thing as a preferred age for at least many archaeological samples. Many dates are of a from-to nature, and cannot be refined as more than min and max ages. As an archaeologist I've had many discussions with both ecologists and geologists who would like us to specify the most probable period (text based identifier for cultural or geological max-min) or calendar date represented by a sample to make API linking or searching easier...

**Comment by dennereed** [comment]
OK I think my suggestion adds more confusion than it solves. Best ignore it.
