### ISSUE TITLE
Review for release

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-chronology#4]
Major changes were committed in 9a0e7d389ff746cd48d00ff2f479f14c4ae9f390. Please review (@lbrensk and @robgur) and comment with acceptance or requests so that I can make a release and push these changes into production at GBIF.

**Comment by lbrensk** [comment]
@tucotuco I looked it over and it looks okay, except that I am not sure why "27" and "14" are in the comments for maximum and minimumChronometricAge? Unless there's something I am forgetting, that could be deleted. The rest looks ok to me! I like this format much better to keep track of our defunct terms.

**Comment by tucotuco** [comment]
Only because that's where they were in that version of the term. The
examples field didn't exist in term_versions.csv nor in terms.csv. They
were in comments in terms.csv. Just preserving the history.

**Comment by tucotuco** [comment]
Changes approved verbally by @lbrensk and @robgur.
